SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768
LEFT_PADDLE_UP_KEY = "w"
LEFT_PADDLE_DN_KEY = "s"
RIGHT_PADDLE_UP_KEY = "Up"
RIGHT_PADDLE_DN_KEY = "Down"
PADDLE_X_OFFSET = 20
PADDLE_Y_OFFSET = 50
BALL_OFF_PADDLE = 20
BALL_STEP = 6
PADDLE_MOVE_STEP_PLAYER = 10
PADDLE_MOVE_STEP_COMP = 3
SCOREBOARD_FONT = ("Courier", 40, "normal")
PAUSE_BEFORE_SERVE_IN_SECS = 1
SCORE_DROPOUT = 5
SCORE_FINAL = 11

serve_options = ["ball.serve_to_left()", "ball.serve_to_right()"]

